package core

import (
	"encoding/base64"
	"encoding/csv"
	"strings"
	"testing"

	"omni_money/backend/database"
	"omni_money/backend/models"
	"omni_money/backend/validation"
)

func TestCSVV3RoundTripPreservesExtendedLedgerDataAndRemapsIDs(t *testing.T) {
	instance, service := openCoreTestService(t, "csv-v3-source")
	_ = instance
	card, err := service.AddTransaction(models.TransactionRequest{Account: "card", Date: "2026-08-01", Item: "coffee", Type: "expense", Amount: 500})
	if err != nil {
		t.Fatal(err)
	}
	bank, err := service.AddTransaction(models.TransactionRequest{Account: "bank", Date: "2026-08-02", Item: "card payment", Type: "expense", Amount: 500})
	if err != nil {
		t.Fatal(err)
	}
	root, err := service.CreateTag("work", nil)
	if err != nil {
		t.Fatal(err)
	}
	child, err := service.CreateTag("coffee", &root.ID)
	if err != nil {
		t.Fatal(err)
	}
	if err := service.AddTransactionTags(card.ID, []int64{child.ID}); err != nil {
		t.Fatal(err)
	}
	if err := service.SaveCreditCardSettings([]string{"card"}); err != nil {
		t.Fatal(err)
	}
	if err := service.SaveBankAccountSettings([]string{"bank"}); err != nil {
		t.Fatal(err)
	}
	if err := service.AddTransactionLink(card.ID, bank.ID); err != nil {
		t.Fatal(err)
	}
	png := []byte("\x89PNG\r\n\x1a\n" + "\x00\x00\x00\x00IEND\xaeB\x60\x82")
	// Use a valid 1x1 fixture generated by the shared image test helper.
	png = encodePNG(t)
	if _, err := service.AddTransactionImage(card.ID, models.TransactionImageRequest{
		Filename: "receipt.png", MimeType: "image/png", Data: base64.StdEncoding.EncodeToString(png),
	}); err != nil {
		t.Fatal(err)
	}

	content, err := service.BackupToCSV()
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(content, "record_type") || !strings.Contains(content, "\n3,transaction,") {
		t.Fatalf("expected CSV v3 export, got header/content: %q", content[:min(len(content), 240)])
	}
	if !strings.Contains(content, "data_base64") || !strings.Contains(content, "receipt.png") {
		t.Fatalf("v3 export did not include image columns: %q", content[:min(len(content), 400)])
	}

	// Import into an independent instance; IDs are allocated independently and
	// all associations must be rebuilt through the source-ID maps.
	target, targetService := openCoreTestService(t, "csv-v3-target")
	if _, err := targetService.ImportCSV(content, "replace"); err != nil {
		t.Fatalf("ImportCSV v3: %v", err)
	}
	var transactionCount, imageCount, tagCount, tagLinkCount, linkCount int
	for query, destination := range map[string]*int{
		"SELECT COUNT(*) FROM transactions":       &transactionCount,
		"SELECT COUNT(*) FROM transaction_images": &imageCount,
		"SELECT COUNT(*) FROM tags":               &tagCount,
		"SELECT COUNT(*) FROM transaction_tags":   &tagLinkCount,
		"SELECT COUNT(*) FROM transaction_links":  &linkCount,
	} {
		if err := target.DB().QueryRow(query).Scan(destination); err != nil {
			t.Fatal(err)
		}
	}
	if transactionCount != 2 || imageCount != 1 || tagCount != 2 || tagLinkCount != 1 || linkCount != 1 {
		t.Fatalf("counts transactions=%d images=%d tags=%d tag-links=%d links=%d", transactionCount, imageCount, tagCount, tagLinkCount, linkCount)
	}
	var credit, bankSetting string
	if err := target.DB().QueryRow("SELECT value FROM settings WHERE key = 'credit_card_items'").Scan(&credit); err != nil {
		t.Fatal(err)
	}
	if err := target.DB().QueryRow("SELECT value FROM settings WHERE key = 'bank_account_items'").Scan(&bankSetting); err != nil {
		t.Fatal(err)
	}
	if credit != `["card"]` || bankSetting != `["bank"]` {
		t.Fatalf("settings = %q/%q", credit, bankSetting)
	}
	if card.ID == 1 && bank.ID == 2 {
		// The source and target normally happen to have the same IDs; force the
		// assertion to use the row's source IDs instead of relying on that fact.
		var targetID int64
		if err := target.DB().QueryRow("SELECT id FROM transactions WHERE item = 'coffee'").Scan(&targetID); err != nil {
			t.Fatal(err)
		}
		if targetID == card.ID {
			t.Log("SQLite allocated matching IDs in independent empty vaults; association checks above still verify remapping")
		}
	}
}

func TestCSVV3RejectsUnsafeVersionAndRollsBackReplace(t *testing.T) {
	setupCoreTestDB(t)
	originalID := insertTestTransaction(t, "keep", "2026-01-01", "original", "income", 100, 100)
	unsafe := strings.Join([]string{
		strings.Join(csvV3Headers, ","),
		"3,transaction,1,,0,0,0,=unsafe,2026-01-01,item,income,100,0,,,,,,,,,,,",
		"3,transaction,2,,0,0,0,cash,2026-01-02,item,expense,50,0,,,,,,,,,,,",
	}, "\n") + "\n"
	if _, err := ImportCSV(unsafe, "replace"); err == nil {
		t.Fatal("unsafe v3 formula cell was accepted")
	}
	var count int
	if err := database.GetDB().QueryRow("SELECT COUNT(*) FROM transactions WHERE id = ?", originalID).Scan(&count); err != nil {
		t.Fatal(err)
	}
	if count != 1 {
		t.Fatalf("original transaction count = %d, want 1 after rollback", count)
	}
}

func TestCSVV3RejectsDuplicateAndUnknownRowsBeforeWriting(t *testing.T) {
	setupCoreTestDB(t)
	base := strings.Join(csvV3Headers, ",") + "\n"
	row := "3,transaction,1,,0,0,0,cash,2026-01-01,item,income,100,0,,,,,,,,,,"
	duplicate := base + row + "\n" + row + "\n"
	if _, err := ImportCSV(duplicate, "replace"); err == nil || !strings.Contains(err.Error(), "重複") {
		t.Fatalf("duplicate v3 transaction result = %v", err)
	}
	unknownFields := append([]string{"3", "unknown"}, make([]string, len(csvV3Headers)-2)...)
	unknown := base + strings.Join(unknownFields, ",") + "\n"
	if _, err := ImportCSV(unknown, "replace"); err == nil || !strings.Contains(err.Error(), "record_type") {
		t.Fatalf("unknown v3 record result = %v", err)
	}
}

func csvV3TestContent(t *testing.T, rows ...map[string]string) string {
	t.Helper()
	var output strings.Builder
	writer := csv.NewWriter(&output)
	if err := writer.Write(csvV3Headers); err != nil {
		t.Fatal(err)
	}
	for _, values := range rows {
		if err := writer.Write(csvV3Record(values)); err != nil {
			t.Fatal(err)
		}
	}
	writer.Flush()
	if err := writer.Error(); err != nil {
		t.Fatal(err)
	}
	return output.String()
}

func TestCSVV3RejectsUnsafeTagSettingsAndCreatedAt(t *testing.T) {
	transaction := map[string]string{
		csvVersionHeader: "3", "record_type": "transaction", "id": "1",
		"account": "cash", "date": "2026-01-01", "item": "item", "type": "income", "amount": "100",
	}
	tests := []struct {
		name string
		row  map[string]string
		want string
	}{
		{
			name: "tag slash",
			row:  map[string]string{csvVersionHeader: "3", "record_type": "tag", "id": "1", "tag_name": "bad/name", "tag_level": "1"},
			want: "タグ名",
		},
		{
			name: "tag parent level",
			row:  map[string]string{csvVersionHeader: "3", "record_type": "tag", "id": "1", "tag_name": "child", "tag_parent_id": "99", "tag_level": "2"},
			want: "タグ親が見つかりません",
		},
		{
			name: "unknown setting",
			row:  map[string]string{csvVersionHeader: "3", "record_type": "setting", "setting_key": "future_secret", "setting_value": "[]"},
			want: "ledger設定キー",
		},
		{
			name: "null setting",
			row:  map[string]string{csvVersionHeader: "3", "record_type": "setting", "setting_key": "credit_card_items", "setting_value": "null"},
			want: "文字列配列JSON",
		},
		{
			name: "duplicate setting item",
			row:  map[string]string{csvVersionHeader: "3", "record_type": "setting", "setting_key": "credit_card_items", "setting_value": `["card","card"]`},
			want: "重複",
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			content := csvV3TestContent(t, transaction, tt.row)
			if _, err := (&Service{}).parseCSVV3(content); err == nil || !strings.Contains(err.Error(), tt.want) {
				t.Fatalf("parse result = %v, want %q", err, tt.want)
			}
		})
	}

	tooLongName := strings.Repeat("a", validation.MaxTagNameBytes+1)
	if _, err := (&Service{}).parseCSVV3(csvV3TestContent(t, map[string]string{
		csvVersionHeader: "3", "record_type": "tag", "id": "1", "tag_name": tooLongName, "tag_level": "1",
	})); err == nil || !strings.Contains(err.Error(), "255バイト") {
		t.Fatalf("long tag result = %v", err)
	}

	root := map[string]string{csvVersionHeader: "3", "record_type": "tag", "id": "1", "tag_name": "root", "tag_level": "1"}
	badChild := map[string]string{csvVersionHeader: "3", "record_type": "tag", "id": "2", "tag_name": "child", "tag_parent_id": "1", "tag_level": "3"}
	if _, err := (&Service{}).parseCSVV3(csvV3TestContent(t, root, badChild)); err == nil || !strings.Contains(err.Error(), "親の階層") {
		t.Fatalf("parent level result = %v", err)
	}

	badImage := map[string]string{
		csvVersionHeader: "3", "record_type": "image", "id": "1", "transaction_id": "1",
		"filename": "receipt.png", "mime_type": "image/png", "data_base64": base64.StdEncoding.EncodeToString(encodePNG(t)),
		"created_at": "not-a-date",
	}
	if _, err := (&Service{}).parseCSVV3(csvV3TestContent(t, transaction, badImage)); err == nil || !strings.Contains(err.Error(), "created_at") {
		t.Fatalf("created_at result = %v", err)
	}
}

func TestCSVV3RequiresExactRecordFieldCount(t *testing.T) {
	content := strings.Join(csvV3Headers, ",") + "\n3,transaction,1\n"
	if _, err := (&Service{}).parseCSVV3(content); err == nil || !strings.Contains(err.Error(), "列数") {
		t.Fatalf("short row result = %v", err)
	}
}

func TestCSVV3AppliesTransactionTextLimits(t *testing.T) {
	base := map[string]string{
		csvVersionHeader: "3", "record_type": "transaction", "id": "1",
		"account": "cash", "date": "2026-01-01", "item": "item", "type": "income", "amount": "100",
	}
	for _, tt := range []struct {
		name, field, want string
		limit             int
	}{
		{name: "account", field: "account", want: "口座名", limit: maxCSVAccountBytes},
		{name: "item", field: "item", want: "項目", limit: maxCSVItemBytes},
		{name: "memo", field: "memo", want: "メモ", limit: maxCSVMemoBytes},
	} {
		t.Run(tt.name, func(t *testing.T) {
			row := make(map[string]string, len(base)+1)
			for key, value := range base {
				row[key] = value
			}
			row[tt.field] = strings.Repeat("x", tt.limit+1)
			if _, err := (&Service{}).parseCSVV3(csvV3TestContent(t, row)); err == nil || !strings.Contains(err.Error(), tt.want) {
				t.Fatalf("%s result = %v", tt.name, err)
			}
		})
	}
}

func TestCSVV3ParsedTextQuotaIsStrict(t *testing.T) {
	parsed := csvV3Import{parsedTextBytes: maxCSVParsedTextBytes}
	if err := parsed.addParsedText("x"); err == nil {
		t.Fatal("parsed text quota accepted data over the limit")
	}
	parsed = csvV3Import{parsedTextBytes: maxCSVParsedTextBytes - 1}
	if err := parsed.addParsedText("x"); err != nil {
		t.Fatalf("last byte of parsed text quota rejected: %v", err)
	}
}

func TestCSVImportReleasesCoreSlotAfterValidationError(t *testing.T) {
	setupCoreTestDB(t)
	invalid := csvV3TestContent(t, map[string]string{
		csvVersionHeader: "3", "record_type": "transaction", "id": "1",
		"account": "cash", "date": "not-a-date", "item": "item", "type": "income", "amount": "100",
	})
	if _, err := ImportCSV(invalid, "replace"); err == nil {
		t.Fatal("invalid CSV unexpectedly imported")
	}
	valid := "account,date,item,type,amount\ncash,2026-01-01,item,income,100\n"
	if count, err := ImportCSV(valid, "append"); err != nil || count != 1 {
		t.Fatalf("valid import after error = count %d, err %v", count, err)
	}
}

func TestCSVV3ReplaceRollsBackAfterDatabaseFailure(t *testing.T) {
	setupCoreTestDB(t)
	originalID := insertTestTransaction(t, "keep", "2026-01-01", "original", "income", 100, 100)
	if _, err := database.GetDB().Exec(`CREATE TRIGGER csv_v3_test_abort
		BEFORE INSERT ON transactions WHEN NEW.account = 'abort'
		BEGIN SELECT RAISE(ABORT, 'test import failure'); END`); err != nil {
		t.Fatal(err)
	}
	content := csvV3TestContent(t,
		map[string]string{csvVersionHeader: "3", "record_type": "transaction", "id": "1", "account": "cash", "date": "2026-01-01", "item": "new", "type": "income", "amount": "100"},
		map[string]string{csvVersionHeader: "3", "record_type": "transaction", "id": "2", "account": "abort", "date": "2026-01-02", "item": "must rollback", "type": "expense", "amount": "50"},
	)
	if _, err := ImportCSV(content, "replace"); err == nil {
		t.Fatal("database failure was not returned")
	}
	var count int
	if err := database.GetDB().QueryRow("SELECT COUNT(*) FROM transactions").Scan(&count); err != nil {
		t.Fatal(err)
	}
	if count != 1 {
		t.Fatalf("transaction count after rollback = %d, want 1", count)
	}
	var item string
	if err := database.GetDB().QueryRow("SELECT item FROM transactions WHERE id = ?", originalID).Scan(&item); err != nil {
		t.Fatal(err)
	}
	if item != "original" {
		t.Fatalf("original transaction item = %q", item)
	}
}

func min(a, b int) int {
	if a < b {
		return a
	}
	return b
}
