// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AcknowledgeDesktopVaultRecovery() {
  return window['go']['main']['App']['AcknowledgeDesktopVaultRecovery']();
}

export function AddTransaction(arg1) {
  return window['go']['main']['App']['AddTransaction'](arg1);
}

export function AddTransactionImage(arg1, arg2) {
  return window['go']['main']['App']['AddTransactionImage'](arg1, arg2);
}

export function AddTransactionLink(arg1, arg2) {
  return window['go']['main']['App']['AddTransactionLink'](arg1, arg2);
}

export function AddTransactionTags(arg1, arg2) {
  return window['go']['main']['App']['AddTransactionTags'](arg1, arg2);
}

export function BackupToCSVFile() {
  return window['go']['main']['App']['BackupToCSVFile']();
}

export function BackupToCSVFull() {
  return window['go']['main']['App']['BackupToCSVFull']();
}

export function ChangeDesktopVaultPassword(arg1, arg2) {
  return window['go']['main']['App']['ChangeDesktopVaultPassword'](arg1, arg2);
}

export function CreateSnapshot() {
  return window['go']['main']['App']['CreateSnapshot']();
}

export function CreateTag(arg1, arg2) {
  return window['go']['main']['App']['CreateTag'](arg1, arg2);
}

export function CreateTagByPath(arg1) {
  return window['go']['main']['App']['CreateTagByPath'](arg1);
}

export function DeleteTag(arg1) {
  return window['go']['main']['App']['DeleteTag'](arg1);
}

export function DeleteTransaction(arg1) {
  return window['go']['main']['App']['DeleteTransaction'](arg1);
}

export function DeleteTransactionImage(arg1) {
  return window['go']['main']['App']['DeleteTransactionImage'](arg1);
}

export function GetAccounts() {
  return window['go']['main']['App']['GetAccounts']();
}

export function GetBalanceHistory() {
  return window['go']['main']['App']['GetBalanceHistory']();
}

export function GetBalanceHistoryFiltered(arg1) {
  return window['go']['main']['App']['GetBalanceHistoryFiltered'](arg1);
}

export function GetBankAccountSettings() {
  return window['go']['main']['App']['GetBankAccountSettings']();
}

export function GetCreditCardSettings() {
  return window['go']['main']['App']['GetCreditCardSettings']();
}

export function GetDesktopVaultStatus() {
  return window['go']['main']['App']['GetDesktopVaultStatus']();
}

export function GetItems(arg1) {
  return window['go']['main']['App']['GetItems'](arg1);
}

export function GetTagDeleteImpact(arg1) {
  return window['go']['main']['App']['GetTagDeleteImpact'](arg1);
}

export function GetTagSummary(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetTagSummary'](arg1, arg2, arg3);
}

export function GetTags() {
  return window['go']['main']['App']['GetTags']();
}

export function GetTransactionImages(arg1) {
  return window['go']['main']['App']['GetTransactionImages'](arg1);
}

export function GetTransactionImagesPage(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetTransactionImagesPage'](arg1, arg2, arg3);
}

export function GetTransactionLinks(arg1) {
  return window['go']['main']['App']['GetTransactionLinks'](arg1);
}

export function GetTransactionTags(arg1) {
  return window['go']['main']['App']['GetTransactionTags'](arg1);
}

export function GetTransactions(arg1, arg2) {
  return window['go']['main']['App']['GetTransactions'](arg1, arg2);
}

export function ImportCSV(arg1, arg2) {
  return window['go']['main']['App']['ImportCSV'](arg1, arg2);
}

export function ImportCSVFile(arg1) {
  return window['go']['main']['App']['ImportCSVFile'](arg1);
}

export function ListSnapshots() {
  return window['go']['main']['App']['ListSnapshots']();
}

export function LockDesktopVault() {
  return window['go']['main']['App']['LockDesktopVault']();
}

export function MigrateLegacyDesktopVault(arg1) {
  return window['go']['main']['App']['MigrateLegacyDesktopVault'](arg1);
}

export function RecoverDesktopVault(arg1, arg2) {
  return window['go']['main']['App']['RecoverDesktopVault'](arg1, arg2);
}

export function RemoveTransactionLink(arg1, arg2) {
  return window['go']['main']['App']['RemoveTransactionLink'](arg1, arg2);
}

export function RemoveTransactionTag(arg1, arg2) {
  return window['go']['main']['App']['RemoveTransactionTag'](arg1, arg2);
}

export function RestoreSnapshot(arg1) {
  return window['go']['main']['App']['RestoreSnapshot'](arg1);
}

export function RotateDesktopVaultRecovery(arg1, arg2) {
  return window['go']['main']['App']['RotateDesktopVaultRecovery'](arg1, arg2);
}

export function SaveBankAccountSettings(arg1) {
  return window['go']['main']['App']['SaveBankAccountSettings'](arg1);
}

export function SaveCreditCardSettings(arg1) {
  return window['go']['main']['App']['SaveCreditCardSettings'](arg1);
}

export function SetupDesktopVault(arg1) {
  return window['go']['main']['App']['SetupDesktopVault'](arg1);
}

export function UnlockDesktopVault(arg1) {
  return window['go']['main']['App']['UnlockDesktopVault'](arg1);
}

export function UpdateTag(arg1, arg2) {
  return window['go']['main']['App']['UpdateTag'](arg1, arg2);
}

export function UpdateTransaction(arg1, arg2) {
  return window['go']['main']['App']['UpdateTransaction'](arg1, arg2);
}
