// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {desktopaccount} from '../models';
import {models} from '../models';
import {main} from '../models';

export function AcknowledgeDesktopVaultRecovery():Promise<desktopaccount.Status>;

export function AddTransaction(arg1:models.TransactionRequest):Promise<models.TransactionResponse>;

export function AddTransactionImage(arg1:number,arg2:models.TransactionImageRequest):Promise<models.TransactionImageResponse>;

export function AddTransactionLink(arg1:number,arg2:number):Promise<void>;

export function AddTransactionTags(arg1:number,arg2:Array<number>):Promise<void>;

export function BackupToCSVFile():Promise<string>;

export function BackupToCSVFull():Promise<string>;

export function ChangeDesktopVaultPassword(arg1:string,arg2:string):Promise<desktopaccount.Status>;

export function CreateSnapshot():Promise<string>;

export function CreateTag(arg1:string,arg2:any):Promise<models.Tag>;

export function CreateTagByPath(arg1:string):Promise<models.Tag>;

export function DeleteTag(arg1:number):Promise<void>;

export function DeleteTransaction(arg1:number):Promise<void>;

export function DeleteTransactionImage(arg1:number):Promise<void>;

export function GetAccounts():Promise<Array<string>>;

export function GetBalanceHistory():Promise<models.BalanceHistoryResponse>;

export function GetBalanceHistoryFiltered(arg1:Array<string>):Promise<models.BalanceHistoryResponse>;

export function GetBankAccountSettings():Promise<Array<string>>;

export function GetCreditCardSettings():Promise<Array<string>>;

export function GetDesktopVaultStatus():Promise<desktopaccount.Status>;

export function GetItems(arg1:string):Promise<Array<string>>;

export function GetTagDeleteImpact(arg1:number):Promise<models.TagDeleteImpact>;

export function GetTagSummary(arg1:string,arg2:string,arg3:string):Promise<Array<models.TagSummary>>;

export function GetTags():Promise<Array<models.Tag>>;

export function GetTransactionImages(arg1:number):Promise<Array<models.TransactionImageResponse>>;

export function GetTransactionImagesPage(arg1:number,arg2:string,arg3:number):Promise<models.TransactionImagePage>;

export function GetTransactionLinks(arg1:number):Promise<Array<models.LinkedTransactionResponse>>;

export function GetTransactionTags(arg1:number):Promise<Array<models.Tag>>;

export function GetTransactions(arg1:string,arg2:string):Promise<Array<models.TransactionResponse>>;

export function ImportCSV(arg1:string,arg2:string):Promise<number>;

export function ImportCSVFile(arg1:string):Promise<number>;

export function ListSnapshots():Promise<Array<string>>;

export function LockDesktopVault():Promise<desktopaccount.Status>;

export function MigrateLegacyDesktopVault(arg1:string):Promise<main.DesktopVaultRecoveryResponse>;

export function RecoverDesktopVault(arg1:string,arg2:string):Promise<main.DesktopVaultRecoveryResponse>;

export function RemoveTransactionLink(arg1:number,arg2:number):Promise<void>;

export function RemoveTransactionTag(arg1:number,arg2:number):Promise<void>;

export function RestoreSnapshot(arg1:string):Promise<void>;

export function RotateDesktopVaultRecovery(arg1:string):Promise<main.DesktopVaultRecoveryResponse>;

export function SaveBankAccountSettings(arg1:Array<string>):Promise<void>;

export function SaveCreditCardSettings(arg1:Array<string>):Promise<void>;

export function SetupDesktopVault(arg1:string):Promise<main.DesktopVaultRecoveryResponse>;

export function UnlockDesktopVault(arg1:string):Promise<desktopaccount.Status>;

export function UpdateTag(arg1:number,arg2:string):Promise<void>;

export function UpdateTransaction(arg1:number,arg2:models.TransactionRequest):Promise<models.TransactionResponse>;
