// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function AddTransaction(arg1:models.TransactionRequest):Promise<models.TransactionResponse>;

export function BackupToCSV():Promise<string>;

export function CreateSnapshot():Promise<string>;

export function DeleteTransaction(arg1:number):Promise<void>;

export function GetAccounts():Promise<Array<string>>;

export function GetBalanceHistory():Promise<models.BalanceHistoryResponse>;

export function GetBalanceHistoryFiltered(arg1:Array<string>):Promise<models.BalanceHistoryResponse>;

export function GetCreditCardSettings():Promise<Array<string>>;

export function GetItems(arg1:string):Promise<Array<string>>;

export function GetTransactions(arg1:string,arg2:string):Promise<Array<models.TransactionResponse>>;

export function Greet(arg1:string):Promise<string>;

export function ImportCSV(arg1:string,arg2:string):Promise<number>;

export function ListSnapshots():Promise<Array<string>>;

export function RestoreSnapshot(arg1:string):Promise<void>;

export function SaveCreditCardSettings(arg1:Array<string>):Promise<void>;

export function UpdateTransaction(arg1:number,arg2:models.TransactionRequest):Promise<models.TransactionResponse>;
